version: '3'
services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"
      - "9000:9000"
    environment:
      CLUSTER_NAME: test
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - hadoop

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    hostname: datanode
    environment:
      CLUSTER_NAME: test
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    depends_on:
      - namenode
    networks:
      - hadoop

  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8080:8080"
    environment:
      INIT_DAEMON_STEP: setup_spark
      SPARK_MASTER_HOST: spark-master
    depends_on:
      - namenode
      - datanode
    networks:
      - hadoop

  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker
    hostname: spark-worker
    ports:
      - "8081:8081"
    environment:
      SPARK_MASTER: spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - hadoop

  pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: pyspark
    hostname: pyspark
    ports:
      - "8888:8888"
    environment:
      SPARK_MASTER: spark://spark-master:7077
    depends_on:
      - spark-master
      - hive-server
    networks:
      - hadoop

  postgres:
    image: postgres:10
    container_name: postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    ports:
      - "5432:5432"
    volumes:
      - metastore_db:/var/lib/postgresql/data
    networks:
      - hadoop

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    hostname: hive-metastore
    environment:
      HIVE_METASTORE_DB_TYPE: postgres
      HIVE_DB: metastore
      HIVE_USER: hive
      HIVE_PASSWORD: hive
      HIVE_METASTORE_HOST: postgres
      SERVICE_PRECONDITION: postgres:5432
      CORE_CONF_fs_defaultFS: hdfs://namenode:8020
    ports:
      - "9083:9083"
    depends_on:
      - postgres
      - namenode
    networks:
      - hadoop

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    hostname: hive-server
    environment:
      HIVE_METASTORE_URI: thrift://hive-metastore:9083
    ports:
      - "10000:10000"
    depends_on:
      - hive-metastore
    networks:
      - hadoop

volumes:
  hadoop_namenode:
  hadoop_datanode:
  metastore_db:

networks:
  hadoop:
    driver: bridge
